#!/bin/bash

## Copyright (C) 2018 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## Copyright (C) 2018 Iry Koon <iry@riseup.net>
## See the file COPYING for copying conditions.

set -x

if [ ! -d /usr/local/etc/torrc.d ]; then
   /usr/bin/install -Z -m 00755 -o root -g root -d /usr/local/etc/torrc.d
fi

if [ ! -e /usr/local/etc/torrc.d/40_tor_control_panel.conf ]; then
   /usr/bin/install -Z -m 00644 -o root -g root -T /usr/share/anon-gw-anonymizer-config/tor_control_panel_torrc_template.conf /usr/local/etc/torrc.d/40_tor_control_panel.conf
fi

if [ ! -e /usr/local/etc/torrc.d/50_user.conf ]; then
   /usr/bin/install -Z -m 00644 -o root -g root -T /usr/share/anon-gw-anonymizer-config/user_torrc_template.conf /usr/local/etc/torrc.d/50_user.conf
fi
