#!/bin/bash

## Copyright (C) 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## Copyright (C) 2018 Iry Koon <iry@riseup.net>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor
#### gateway_only yes
#### description
## helper script for <code>anon-verify</code>
#### meta end

#set -ex

temp_verbose_torrc=$(mktemp)

declare -a torrc_files

function parser() {
   for abs_path in "$@"; do
      local abs="$abs_path"
      if [[ -f "$abs_path" ]]; then
         echo "===> Parsing file $abs_path" >> "$temp_verbose_torrc"
         torrc_files+=("$abs_path")
         local file_content
         file_content="$(cat "$abs")"
         IFS=$'\n'
         ## only show comments in torrc files when $VERY_VERBOSE is "1"
         for line in $file_content; do
            if [[ "$line" =~ ^[[:space:]]*# && "$VERY_VERBOSE" != "1" ]]; then
               continue
            else
               echo "$line" >> "$temp_verbose_torrc"
            fi

            if [[ "$line" =~ ^[[:space:]]*%include ]]; then
               parser "$(echo "$line" | awk '{print $2;}')"
            fi
         done
      elif [[ -d "$abs_path" ]]; then
         echo "===> Parsing folder $abs_path" >> "$temp_verbose_torrc"
         parser "$(find "$abs_path" -mindepth 1 | sort -g)"
      else
         echo "ERROR: invalid file: '$abs_path'"
      fi
      echo "===> Done parsing $abs" >> "$temp_verbose_torrc"
   done
}

function parsing_order_verbose(){
   echo "The Tor configuration files are parsed in such order: "
   cat "$temp_verbose_torrc"
}

function used_torrc_files(){
   echo "${#torrc_files[@]} files are used as Tor configuration files: "
   echo "${torrc_files[@]}"
}

function unknown_option_specifier(){
   for unknown_option in "$@"; do
      echo "The following files contain unkown option '$unknown_option': "
      grep -iHnE --color "^([[:space:]])*$unknown_option" "${torrc_files[@]}"
      echo "Please modify these files to fix the problem."
   done
}

#parser $@
#parsing_order_verbose
#used_torrc_files
#unknown_option_specifier "bridge" "control"
