.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ANON\-VERIFY" "8" "January 2020" "anon-gw-anonymizer-config" "anon-gw-anonymizer-config Manual"
.SH "NAME"
\fBanon\-verify\fR \- Tor configuration verification tool
.SH "SYNOPSIS"
\fBanon\-verify [OPTION]\fR
.SH "DESCRIPTION"
anon\-verify is a user\-friendly wrapper around the Tor \-\-verify\-config in Whonix\. It will do a proper Tor configuration verification and then generate an easy to understand report with useful suggestions\.
.P
\-h, \-\-help
.IP "" 4
.nf
display this help and exit
.fi
.IP "" 0
.P
\-v, \-\-verbose
.IP "" 4
.nf
show an additional report on how Tor configuration is parsed, excluding comments in the configuration files
.fi
.IP "" 0
.P
\-vv, \-\-very\-verbose
.IP "" 4
.nf
show an additional report on how Tor configuration is parsed, including comments in the configuration files
.fi
.IP "" 0
.SH "AUTHOR"
This man page has been written by Iry Koon (iry@riseup\.net)\.
.SH "COPYRIGHT"
Copyright (C) 2018 \- 2025 ENCRYPTED SUPPORT LLC \fIadrelanos@whonix\.org\fR
.P
Copyright (C) 2018 Iry Koon \fIiry@riseup\.net\fR
.P
See the file COPYING for copying conditions\.
