.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "ANON\-INFO" "8" "January 2020" "anon-gw-anonymizer-config" "anon-gw-anonymizer-config Manual"
.SH "NAME"
\fBanon\-info\fR \- shows Tor apt repository status and Tor package version
.SH "SYNOPSIS"
\fBanon\-info\fR
.SH "DESCRIPTION"
Shows non\-comment deb lines in /etc/apt/sources\.list\.d/ and the version number of the 'tor' package\.
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
