.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "ANON\-LOG" "8" "January 2020" "anon-gw-anonymizer-config" "anon-gw-anonymizer-config Manual"
.SH "NAME"
\fBanon\-log\fR \- Tor log parser
.SH "SYNOPSIS"
\fBanon\-log\fR
.SH "DESCRIPTION"
anon\-log is a user\-friendly wrapper around the journalctl in Whonix to view Tor related log entries while filtering out irrelevant log output, non\-issues\.
.SH "WEB"
https://www\.whonix\.org/wiki/Tor#Log_Analysis
.P
https://www\.whonix\.org/wiki/Tor#Non\-Issues
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)
