.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ONION\-GRATER\-REMOVE" "8" "January 2020" "anon-gw-anonymizer-config" "anon-gw-anonymizer-config Manual"
.SH "NAME"
\fBonion\-grater\-remove\fR \- remove onion\-grater profile form onion\-grater configuration
.SH "SYNOPSIS"
\fBonion\-grater\-remove\fR profile\-name
.SH "DESCRIPTION"
Removes onion\-grater profile form onion\-grater configuration\.
.P
Removes any symlinks that matches \fB/usr/local/etc/onion\-grater\-merger\.d/*_${profile_name}\.yml\fR\.
.P
Folder \fB/etc/onion\-grater\-merger\.d/\fR is ignored\.
.SH "EXAMPLE"
\fBsudo onion\-grater\-remove onionshare\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
