.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ONION\-GRATER\-LIST" "8" "January 2020" "anon-gw-anonymizer-config" "anon-gw-anonymizer-config Manual"
.SH "NAME"
\fBonion\-grater\-list\fR \- list onion\-grater profile to onion\-grater configuration
.SH "SYNOPSIS"
\fBonion\-grater\-list\fR [\-\-available|\-\-used] \-\-show
.SH "DESCRIPTION"
List onion\-grater profiles available or in use, optinally print file contents\.
.SH "EXAMPLE"
\fBsudo onion\-grater\-list \-\-available \-\-show\fR \fBsudo onion\-grater\-list \-\-used \-\-show\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
