#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

cat /etc/motd

sudo service tor@default reload

sudo service tor@default status
true "$?"

true "Feel free to close this window."

sleep 86400
