#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

cat /etc/motd

sudo service tor@default restart

sudo service tor@default status

true "$?"

true "Feel free to close this window."

sleep 86400
