#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description
## wrapper to restart Tor
#### meta end

set -x

cat /etc/motd

sudo systemctl --no-pager restart tor@default

sudo systemctl --no-pager status tor@default

true "$?"

true "Feel free to close this window."

sleep 86400
