#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description
## wrapper to open folder <code>/var/lib/tor</code> in default file manager
## using graphical sudo.
#### meta end

set -x

if command -v lxsudo &>/dev/null ; then
   x_sudo=lxsudo
elif command -v kdesudo &>/dev/null ; then
   x_sudo=kdesudo
elif command -v gksudo &>/dev/null ; then
   x_sudo=gksudo
fi

## https://bugzilla.xfce.org/show_bug.cgi?id=15282
## https://github.com/lxqt/lxqt-sudo/issues/114
$x_sudo env XDG_CURRENT_DESKTOP=X-Generic xdg-open /var/lib/tor
