#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

if command -v thunar &>/dev/null ; then
   file_manager=thunar
elif command -v dolphin &>/dev/null ; then
   file_manager=dolphin
fi

if command -v kdesudo &>/dev/null ; then
   x_sudo=kdesudo
elif command -v gksudo &>/dev/null ; then
   x_sudo=gksudo
fi

$x_sudo $file_manager /var/lib/tor
