#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

if command -v lxsu &>/dev/null ; then
   x_sudo=lxsu
elif command -v kdesudo &>/dev/null ; then
   x_sudo=kdesudo
elif command -v gksudo &>/dev/null ; then
   x_sudo=gksudo
fi

## https://bugzilla.xfce.org/show_bug.cgi?id=15282
## https://github.com/lxqt/lxqt-sudo/issues/114
$x_sudo env XDG_CURRENT_DESKTOP=X-Generic xdg-open /var/lib/tor
