#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description

## https://bugzilla.xfce.org/show_bug.cgi?id=15282
## https://github.com/lxqt/lxqt-sudo/issues/114
## https://forums.whonix.org/t/use-sudoedit-in-whonix-documentation-and-whonix-software/7599/30
lxsudo sudo -u "$(whoami)" env VISUAL="$VISUAL" sudoedit /usr/local/etc/torrc.d/50_user.conf

#### meta end
