#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY xdg-open /usr/local/etc/torrc.d/50_user.conf
