#!/bin/bash

## Copyright (C) 2020 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x

true "$0: START"

qubes_replace_ips_maybe() {
  if ! test -f /usr/share/qubes/marker-vm ; then
    true "$0: INFO: Do not run replace-ips since not running inside Qubes."
    return 0
  fi
  true "$0: INFO: Running inside Qubes."
  if test -f /run/qubes/this-is-templatevm ; then
    true "$0: INFO: Do not run replace-ips since running inside Qubes Template."
    return 0
  fi
  true "$0: INFO: Not running inside Qubes Template."
  ## XXX: duplicated in 'qubes-whonix-postinit.service'
  ## Replace IP addresses in known configuration files / scripts with
  ## currently discovered IP address.
  /usr/lib/qubes-whonix/replace-ips
}

tor_wait_for_network_maybe() {
  if test -f /run/qubes/this-is-templatevm ; then
    true "$0: INFO: Do not run tor-wait-for-network inside Qubes Template."
    return 0
  fi
  true "$0: INFO: Not running inside Qubes Template."
  /usr/libexec/anon-gw-anonymizer-config/tor-wait-for-network
}

/usr/libexec/anon-gw-anonymizer-config/make-sure-torrc-exist

/usr/libexec/helper-scripts/repair-torrc

true "$0: INFO: Wait for IPv6..."
tor_wait_for_network_maybe

true "$0: INFO: Conditionally disable IPv6, if unavailable..."
/usr/libexec/anon-gw-anonymizer-config/generate-tor-service-defaults-torrc-anondist

qubes_replace_ips_maybe

true "$0: END"
