#!/bin/bash

## Copyright (C) 2020 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

true "$0: START"

/usr/libexec/anon-gw-anonymizer-config/make-sure-torrc-exist
/usr/libexec/helper-scripts/repair-torrc

true "$0: END"
