#!/bin/bash

## Copyright (C) 2019 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor
#### gateway_only yes
#### description
## Move files in folder /usr/local/etc/torrc.d/ and /etc/torrc.d/ that do not
## end with '.conf' out of the way.
#### meta end

#set -x
set -e
set -o pipefail

error_handler() {
   local exit_code="$?"
   echo "$0 ERROR: exit_code: $exit_code | BASH_COMMAND: $BASH_COMMAND"
   exit 1
}

trap error_handler ERR

echo "$0 INFO: start."

shopt -s nullglob
shopt -s dotglob

## testing
# mkdir -p /etc/torrc.d
# mkdir -p /usr/local/etc/torrc.d
# touch /etc/torrc.d/30_junk.conf.dpkg-old
# touch /usr/local/etc/torrc.d/40_junk2.conf.dpkg-olds

for file_name in /etc/torrc.d/* /usr/local/etc/torrc.d/* ; do
   true "file_name: $file_name"
   if [ -d "$file_name" ]; then
      ## Ignore subfolders such as our own backup folder.
      true "skip folder: $file_name"
      continue
   fi
   base_name="${file_name##*/}"
   file_extension="${base_name##*.}"
   if [ "$file_extension" = "conf" ]; then
      true "good: $file_name"
      continue
   fi
   ## Avoid moving
   ## /etc/torrc.d/95_whonix.conf
   ## to
   ## /etc/torrc.d/backup/95_whonix.conf.dpkg-new
   ## during anon-gw-anonymizer-config package upgrades.
   if [ "$file_extension" = "dpkg-new" ]; then
      echo "INFO: dpkg-new file found: $file_name"
      continue
   fi
   true "extraneous: $file_name"
   dir_name="${file_name%/*}"
   mkdir -p "${dir_name}/backup"
   mv --verbose --backup=numbered --force "$file_name" "${dir_name}/backup/"
done

echo "$0 INFO: success."
