#!/bin/bash

## Copyright (C) 2012 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description
## wrapper to start nxy
#### meta end

set -x

cat /etc/motd

nyx

true "Feel free to close this window."

sleep 86400
