#!/bin/bash

## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description
## wrapper to reload Tor
#### meta end

set -x

cat /etc/motd

if sudo /usr/sbin/service tor@default status &>/dev/null ; then
   sudo systemctl --no-pager reload tor@default
else
   sudo systemctl --no-pager restart tor@default
fi

sudo systemctl --no-pager status tor@default
true "$?"

true "Feel free to close this window."

sleep 86400
