#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description
## wrapper to reload Tor
#### meta end

set -x

cat /etc/motd

if sudo /usr/sbin/service tor@default status &>/dev/null ; then
   leaprun reload-tor
else
   leaprun restart-tor
fi

leaprun tor-status
true "$?"

true "Feel free to close this window."

sleep 86400
