#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description
## wrapper to stop Tor
#### meta end

set -x

cat /etc/motd

sudo systemctl --no-pager stop tor@default

sudo systemctl --no-pager status tor@default
true "$?"

true "Feel free to close this window."

sleep 86400
