#!/bin/bash

## Copyright (C) 2012 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description
## wrapper to open folder <code>/var/lib/tor</code> in default file manager
## using graphical sudo.
#### meta end

set -x

## https://bugzilla.xfce.org/show_bug.cgi?id=15282
## https://github.com/lxqt/lxqt-sudo/issues/114
## TODO: native Wayland support

lxqt-sudo env XDG_CURRENT_DESKTOP=X-Generic xdg-open /var/lib/tor
