#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

source /usr/libexec/helper-scripts/use_sudo.sh
sudo_error_exit_if_unavailable

set -x

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description

## https://bugzilla.xfce.org/show_bug.cgi?id=15282
## https://github.com/lxqt/lxqt-sudo/issues/114
## https://forums.whonix.org/t/use-sudoedit-in-whonix-documentation-and-whonix-software/7599/30
gsudoedit /usr/local/etc/torrc.d/50_user.conf

#### meta end
