#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category tor and usability
#### gateway_only yes
#### description
## wrapper to show Tor configuration examples
#### meta end

set -x

xdg-open /usr/share/anon-gw-anonymizer-config/torrc.examples
